services:
  # ── SQL Server Database ────────────────────────────────────
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skinvision-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SkinVision@2026!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "SkinVision@2026!" -Q "SELECT 1" -C -b
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # ── .NET 9 Backend API ─────────────────────────────────────
  api:
    build:
      context: .
      dockerfile: SkinVision.API/Dockerfile
    container_name: skinvision-api
    ports:
      - "5163:5163"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db;Database=SkinVisionDB;User Id=sa;Password=SkinVision@2026!;TrustServerCertificate=True;
      - Jwt__Key=SkinVision_Graduation_Project_2026_SecretKey!
      - Jwt__Issuer=SkinVision
      - Jwt__Audience=SkinVision
      - DlService__BaseUrl=http://ml:8000
      - Frontend__BaseUrl=http://frontend
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID:-985994639568-j35bjirlisulbadm2hf8ufrshmb347a2.apps.googleusercontent.com}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET:-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}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/wwwroot/uploads

  # ── Python ML Service (FastAPI + PyTorch) ──────────────────
  ml:
    build:
      context: ./SkinVision.ML
      dockerfile: Dockerfile
    container_name: skinvision-ml
    ports:
      - "8000:8000"
    environment:
      - SKINVISION_MODEL_PATH=/app/model/EfficientNet_B3_model.pth

  # ── Angular Frontend (Nginx) ───────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skinvision-frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  sqldata:
  uploads:
